### PR TITLE
Use password authentication with RabbitMQ

### LINKED ISSUE #197: adding credentials to rabbitmq
adding credentials to rabbitmq

### PR DESCRIPTION
**Pull request by sajith**
Resolves #197.

### CODE REVIEW

**Review by italovalcy — COMMENTED** [review]
Hi @sajith excellent to see you already have submitted a code to handle RabbitMQ auth, which is an important step on the environment setup (since Luis setup is also using authentication). The code seems clear and neat. Very nice!

I just have one doubt. I do see `pika.ConnectionParameters` being used on other places that you didn't cover on this PR, as well as `RabbitMqServerConfigure` which references  MQ_HOST variable.

can you please take a look on the following occurrences:

```
./sdx_controller/messaging/topic_queue_consumer.py:MQ_HOST = os.environ.get("MQ_HOST")
./sdx_controller/messaging/topic_queue_consumer.py:            pika.ConnectionParameters(host=MQ_HOST)
./sdx_controller/messaging/topic_queue_consumer.py:    #         pika.ConnectionParameters(host=MQ_HOST)
./sdx_controller/messaging/message_queue_consumer.py:MQ_HOST = os.environ.get("MQ_HOST")
./sdx_controller/messaging/message_queue_consumer.py:    def __init__(self, host=MQ_HOST, queue="hello"):
./sdx_controller/messaging/message_queue_consumer.py:    serverconfigure = RabbitMqServerConfigure(host=MQ_HOST, queue="hello")
./sdx_controller/messaging/rpc_queue_producer.py:MQ_HOST = os.environ.get("MQ_HOST")
./sdx_controller/messaging/rpc_queue_producer.py:            pika.ConnectionParameters(host=MQ_HOST)
./sdx_controller/messaging/topic_queue_producer.py:MQ_HOST = os.environ.get("MQ_HOST")
./sdx_controller/messaging/topic_queue_producer.py:            pika.ConnectionParameters(host=MQ_HOST)
./sdx_controller/messaging/topic_queue_producer.py:        #     self.connection = pika.BlockingConnection(pika.ConnectionParameters(host=MQ_HOST))
```

**Comment by italovalcy** [comment]
> Hi @sajith excellent to see you already have submitted a code to handle RabbitMQ auth, which is an important step on the environment setup (since Luis setup is also using authentication). The code seems clear and neat. Very nice!
> 
> I just have one doubt. I do see `pika.ConnectionParameters` being used on other places that you didn't cover on this PR, as well as `RabbitMqServerConfigure` which references MQ_HOST variable.
> 
> can you please take a look on the following occurrences:
> 
> ```
> ./sdx_controller/messaging/topic_queue_consumer.py:MQ_HOST = os.environ.get("MQ_HOST")
> ./sdx_controller/messaging/topic_queue_consumer.py:            pika.ConnectionParameters(host=MQ_HOST)
> ./sdx_controller/messaging/topic_queue_consumer.py:    #         pika.ConnectionParameters(host=MQ_HOST)
> ./sdx_controller/messaging/message_queue_consumer.py:MQ_HOST = os.environ.get("MQ_HOST")
> ./sdx_controller/messaging/message_queue_consumer.py:    def __init__(self, host=MQ_HOST, queue="hello"):
> ./sdx_controller/messaging/message_queue_consumer.py:    serverconfigure = RabbitMqServerConfigure(host=MQ_HOST, queue="hello")
> ./sdx_controller/messaging/rpc_queue_producer.py:MQ_HOST = os.environ.get("MQ_HOST")
> ./sdx_controller/messaging/rpc_queue_producer.py:            pika.ConnectionParameters(host=MQ_HOST)
> ./sdx_controller/messaging/topic_queue_producer.py:MQ_HOST = os.environ.get("MQ_HOST")
> ./sdx_controller/messaging/topic_queue_producer.py:            pika.ConnectionParameters(host=MQ_HOST)
> ./sdx_controller/messaging/topic_queue_producer.py:        #     self.connection = pika.BlockingConnection(pika.ConnectionParameters(host=MQ_HOST))
> ```

@sajith if you allow my contribution here, below is a augmented version of the changes you made to also include the files above (I tried to follow the same approach/code-style as you):

```
diff --git a/sdx_controller/messaging/message_queue_consumer.py b/sdx_controller/messaging/message_queue_consumer.py
index af4f71b..6485d96 100644
--- a/sdx_controller/messaging/message_queue_consumer.py
+++ b/sdx_controller/messaging/message_queue_consumer.py
@@ -3,7 +3,10 @@ import os

 import pika

-MQ_HOST = os.environ.get("MQ_HOST")
+MQ_HOST = os.getenv("MQ_HOST")
+MQ_PORT = os.getenv("MQ_PORT") or 5672
+MQ_USER = os.getenv("MQ_USER") or "guest"
+MQ_PASS = os.getenv("MQ_PASS") or "guest"


 class MessageQueue:
@@ -21,8 +24,18 @@ class MetaClass(type):


 class RabbitMqServerConfigure(metaclass=MetaClass):
-    def __init__(self, host=MQ_HOST, queue="hello"):
+    def __init__(
+        self,
+        host=MQ_HOST,
+        port=MQ_PORT,
+        username=MQ_USER,
+        password=MQ_PASS,
+        queue="hello",
+    ):
         self.host = host
+        self.port = port
+        self.username = username
+        self.password = password
         self.queue = queue


@@ -30,7 +43,14 @@ class rabbitmqServer:
     def __init__(self, server):
         self.server = server
         self._connection = pika.BlockingConnection(
-            pika.ConnectionParameters(host=self.server.host)
+            pika.ConnectionParameters(
+                host=self.server.host,
+                port=self.server.port,
+                credentials=pika.PlainCredentials(
+                    username=self.server.username,
+                    password=self.server.password,
+                ),
+            )
         )
         self._channel = self._connection.channel()
         self._tem = self._channel.queue_declare(queue=self.server.queue)
@@ -54,7 +74,13 @@ class rabbitmqServer:


 if __name__ == "__main__":
-    serverconfigure = RabbitMqServerConfigure(host=MQ_HOST, queue="hello")
+    serverconfigure = RabbitMqServerConfigure(
+        host=MQ_HOST,
+        port=MQ_PORT,
+        username=MQ_USER,
+        password=MQ_PASS,
+        queue="hello",
+    )

     server = rabbitmqServer(server=serverconfigure)
     server.startserver()
diff --git a/sdx_controller/messaging/rpc_queue_producer.py b/sdx_controller/messaging/rpc_queue_producer.py
index 357ffbe..dce3900 100644
--- a/sdx_controller/messaging/rpc_queue_producer.py
+++ b/sdx_controller/messaging/rpc_queue_producer.py
@@ -7,14 +7,21 @@ import uuid

 import pika

-MQ_HOST = os.environ.get("MQ_HOST")
+MQ_HOST = os.getenv("MQ_HOST")
+MQ_PORT = os.getenv("MQ_PORT") or 5672
+MQ_USER = os.getenv("MQ_USER") or "guest"
+MQ_PASS = os.getenv("MQ_PASS") or "guest"


 class RpcProducer(object):
     def __init__(self, timeout, exchange_name, routing_key):
         self.logger = logging.getLogger(__name__)
         self.connection = pika.BlockingConnection(
-            pika.ConnectionParameters(host=MQ_HOST)
+            pika.ConnectionParameters(
+                host=MQ_HOST,
+                port=MQ_PORT,
+                credentials=pika.PlainCredentials(username=MQ_USER, password=MQ_PASS),
+            )
         )

         self.channel = self.connection.channel()
diff --git a/sdx_controller/messaging/topic_queue_consumer.py b/sdx_controller/messaging/topic_queue_consumer.py
index e1b4ccf..926d052 100644
--- a/sdx_controller/messaging/topic_queue_consumer.py
+++ b/sdx_controller/messaging/topic_queue_consumer.py
@@ -6,18 +6,25 @@ from queue import Queue

 import pika

-MQ_HOST = os.environ.get("MQ_HOST")
+MQ_HOST = os.getenv("MQ_HOST")
+MQ_PORT = os.getenv("MQ_PORT") or 5672
+MQ_USER = os.getenv("MQ_USER") or "guest"
+MQ_PASS = os.getenv("MQ_PASS") or "guest"
 # subscribe to the corresponding queue
-SUB_QUEUE = os.environ.get("SUB_QUEUE")
-SUB_TOPIC = os.environ.get("SUB_TOPIC")
-SUB_EXCHANGE = os.environ.get("SUB_EXCHANGE")
+SUB_QUEUE = os.getenv("SUB_QUEUE")
+SUB_TOPIC = os.getenv("SUB_TOPIC")
+SUB_EXCHANGE = os.getenv("SUB_EXCHANGE")


 class TopicQueueConsumer(object):
     def __init__(self, thread_queue, exchange_name):
         self.logger = logging.getLogger(__name__)
         self.connection = pika.BlockingConnection(
-            pika.ConnectionParameters(host=MQ_HOST)
+            pika.ConnectionParameters(
+                host=MQ_HOST,
+                port=MQ_PORT,
+                credentials=pika.PlainCredentials(username=MQ_USER, password=MQ_PASS),
+            )
         )

         self.channel = self.connection.channel()
diff --git a/sdx_controller/messaging/topic_queue_producer.py b/sdx_controller/messaging/topic_queue_producer.py
index 3d10575..4c9710b 100644
--- a/sdx_controller/messaging/topic_queue_producer.py
+++ b/sdx_controller/messaging/topic_queue_producer.py
@@ -6,7 +6,10 @@ import uuid

 import pika

-MQ_HOST = os.environ.get("MQ_HOST")
+MQ_HOST = os.getenv("MQ_HOST")
+MQ_PORT = os.getenv("MQ_PORT") or 5672
+MQ_USER = os.getenv("MQ_USER") or "guest"
+MQ_PASS = os.getenv("MQ_PASS") or "guest"


 class TopicQueueProducer(object):
@@ -15,7 +18,11 @@ class TopicQueueProducer(object):
     def __init__(self, timeout, exchange_name, routing_key):
         self.logger = logging.getLogger(__name__)
         self.connection = pika.BlockingConnection(
-            pika.ConnectionParameters(host=MQ_HOST)
+            pika.ConnectionParameters(
+                host=MQ_HOST,
+                port=MQ_PORT,
+                credentials=pika.PlainCredentials(username=MQ_USER, password=MQ_PASS),
+            )
         )

         self.channel = self.connection.channel()
```

**Comment by lmarinve** [comment]
Thank you for the update, @sajith! I will now test using the main branch with this change.

**Comment by sajith** [comment]
@italovalcy Good catch Italo!  Thank you.  And sorry about the latency -- I've been away.  As you've noticed, in this PR, I only addressed the subscribe part, and I missed the publish part.

There are two places where SDX Controller uses the message queue.  This is where it listens for incoming messages:

https://github.com/atlanticwave-sdx/sdx-controller/blob/b8e5f2256faef8d78466c70978d89caa6db66595/sdx_controller/__init__.py#L25-L32

And this is where it publishes:

https://github.com/atlanticwave-sdx/sdx-controller/blob/b8e5f2256faef8d78466c70978d89caa6db66595/sdx_controller/handlers/connection_handler.py#L78-L81

That is it, as far as I know.  There are several classes under `sdx_controller/messaging`, but I am not familiar with them.  It probably would be useful to simplify the code under that directory and remove the unused code (or make it a library that both sdx-controller and sdx-lc can use), but I am not sure how/when to do that or if it is worth the effort. I believe @congwang09 might have opinions on it.

Your contributions are totally welcome, and your approach is certainly better. Would you be willing to start a PR?

**Comment by lmarinve** [comment]
Good afternoon, I suggested isolating the RabbitMQ process from other submodules as a microservice. like here: https://github.com/atlanticwave-sdx/sdx-continuous-development/commit/e7cfa4151312661b3d26adfaaa3fc96cc8310f18

**Comment by italovalcy** [comment]
> @italovalcy Good catch Italo! Thank you. And sorry about the latency -- I've been away. As you've noticed, in this PR, I only addressed the subscribe part, and I missed the publish part.
> 
> There are two places where SDX Controller uses the message queue. This is where it listens for incoming messages:
> 
> https://github.com/atlanticwave-sdx/sdx-controller/blob/b8e5f2256faef8d78466c70978d89caa6db66595/sdx_controller/__init__.py#L25-L32
> 
> And this is where it publishes:
> 
> https://github.com/atlanticwave-sdx/sdx-controller/blob/b8e5f2256faef8d78466c70978d89caa6db66595/sdx_controller/handlers/connection_handler.py#L78-L81
> 
> That is it, as far as I know. There are several classes under [sdx_controller/messaging](https://github.com/atlanticwave-sdx/sdx-controller/tree/main/sdx_controller/messaging), but I am not very familiar with them. It probably would be useful to simplify the code under that directory and remove the unused code (or make it a library that both sdx-controller and sdx-lc can use), but I am not sure if/when to do that or if it is worth the effort. I believe @congwang09 might have opinions on it.
> 
> Your contributions are totally welcome, and your approach is certainly better. Would you be willing to start a PR?

Hi @sajith great points you raised. Thanks for continue the discussion and I agree with you regarding simplifying the code under `messaging` folder. I also agree with the strategy you mentioned about we having another PR as an addition to this one with the missing files I mentioned above. And I'm willing to contribute authoring the new PR. Let's do this: following the above comments, I will open an issue to let @congwang09 and @YufengXin decide what can be simplified under messaging folder, as well as work in a new PR that will sits over this one with the missing changes.

Thanks again for you comments, @sajith!

**Comment by italovalcy** [comment]
> Hi @sajith great points you raised. Thanks for continue the discussion and I agree with you regarding simplifying the code under `messaging` folder. I also agree with the strategy you mentioned about we having another PR as an addition to this one with the missing files I mentioned above. And I'm willing to contribute authoring the new PR. Let's do this: following the above comments, I will open an issue to let @congwang09 and @YufengXin decide what can be simplified under messaging folder, as well as work in a new PR that will sits over this one with the missing changes.
> 
> Thanks again for you comments, @sajith!

Opened Issue https://github.com/atlanticwave-sdx/sdx-controller/issues/249 to discuss code cleaning opportunities under `messaging` subfolder. Opened PR #250 to handle additional changes for RabbitMQ authentication.

@sajith with that said, I will update my review and approve your PR.

**Review by italovalcy — APPROVED** [review]
LGTM

**Pull request merged**
