### PR TITLE
299 sdx controller must have new endpoints according to specification 20

### PR DESCRIPTION
**Pull request by YufengXin**
spec v2: 
1. /connection -> /l2vpn
2. adding the patch method

### CODE REVIEW

**Comment by YufengXin** [comment]
there are a few "unused" classes in models: for v2 and other future implementaton

**Comment by sajith** [comment]
> there are a few "unused" classes in models: for v2 and other future implementation

It probably might be better to not use the generated models at all?  A better way might be to write the models using pydantic in datamodel, and use them in the handlers and tests.  That way we will be using Swagger Studio (or other tools) only to design the OpenAPI spec.  I wrote up an issue about this: https://github.com/atlanticwave-sdx/datamodel/issues/144.

From my quick testing, I think pydantic might work just fine for us.  This might also solve https://github.com/atlanticwave-sdx/datamodel/issues/92 in an elegant way.

**Comment by YufengXin** [comment]
Right! I'll learn and do...Thx

**Comment by sajith** [comment]
I am only weakly proposing this for now, to see if there is anything that I am missing because I have no experience with the current workflow (of generating code and updating it in sdx-controller and elsewhere).  I will try writing some code with pydantic and see how well things work, and then propose changes more strongly if my assumptions about how things might work turn out to be true. :-)

We have higher priority things to do for now anyway.  So this might be after October or so.

**Pull request merged**
