### PR TITLE
Enable check and test for all branches

### PR DESCRIPTION
**Pull request by congwang09**
Enable check and test for all branches and all commits.

### CODE REVIEW

**Review by sajith — COMMENTED** [review]
Unless I misunderstood something, these changes do not do anything new.  Tests are already run against a PR branch on every push.  That is what `pull_request:` means; we do not need a `branches:` under that.

**Comment by congwang09** [comment]
Before this change, github actions only run code checks and tests after the PR is created. This change lets us see failed tests before the PR is created.

Screenshot 2024-06-13 at 10 15 47 AM

After the change the checks run on every commit:

Screenshot 2024-06-13 at 10 18 47 AM

**Comment by sajith** [comment]
Ah, so you want to run tests against every commit.  The trouble with that is, we only get a limited number of free CI time (3000 minutes per month) on GitHub's infrastructure.  We will quickly run out of that resource if we run tests against every commit.

It is good enough that main branch passes tests, and code that we merge into the main branch passes tests.

**Comment by congwang09** [comment]
> Ah, so you want to run tests against every commit. The trouble with that is, we only get a limited number of free CI time (3000 minutes per month) on GitHub's infrastructure. We will quickly run out of that resource if we run tests against every commit.
> 
> It is good enough that main branch passes tests, and code that we merge into the main branch passes tests.

Oh I see. that makes sense. I'll close this PR.

**Pull request closed without merging**
